### PR TITLE
Update skeleton.xml

### PR DESCRIPTION
**Pull request by diegorodriguesvieira**

### CODE REVIEW

**Comment by LuisPro** [comment]
I thought @peonso did all monsters from cip files?

**Comment by peonso** [comment]
But I did it manually, might have missed something, can someone confirm it?

**Comment by diegorodriguesvieira** [comment]
The skeleton is moving very fast...

**Comment by diegorodriguesvieira** [comment]
@peonso I forgot to close the previousPR...

**Comment by diegorodriguesvieira** [comment]
@peonso approve this PR to fix a critical crash....
thanks

**Pull request merged**
