### PR TITLE
example wrong rune weight

### PR DESCRIPTION
**Pull request by LuisPro**
runes weight is wrong

### CODE REVIEW

**Comment by peonso** [comment]
All of them should weigh 1.20 oz. Right?

**Comment by LuisPro** [comment]
I think yes. Im not sure about charges. Uhs was 100% x1. Hmms was 100% x5.
But dont remember about sds?
On rl map there is a lot sds in houses x1.
But i have some flashback memories when i make sd it was x3..
Im so confused.

**Comment by peonso** [comment]
It's 1x, I'm fixing wrong charges and rune names also, based on leaked files.

**Comment by LuisPro** [comment]
Ok, Thanks.

**Pull request closed without merging**
